[package]
name = "lattice-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
async-trait.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
chrono.workspace = true
snmp.workspace = true
futures-util.workspace = true
reqwest.workspace = true

[dev-dependencies]
axum.workspace = true
